import numpy as np
import matplotlib.pyplot as plt
import os
import importlib.util
import sys
import odl
import yaml
from functools import partial

def create_pykats_config(curved=False, test=1, complex_phantom=False, shifts=None):  
    """Create and synchronize PyKatsevich and ODL configurations for helical CT comparison.

    This function sets up a consistent configuration between the PyKatsevich and ODL 
    libraries by:
      - Loading a YAML configuration file used by PyKatsevich.
      - Initializing system geometry and phantom objects from PyKatsevich modules.
      - Creating the corresponding geometry and reconstruction space in ODL.
      - Generating a 3D phantom and computing sinograms using both PyKatsevich and ODL.
      - Saving visualizations of phantom and sinograms for direct comparison.

    This utility is useful for validating that geometries, phantoms, and projection 
    pipelines between PyKatsevich and ODL are aligned for helical CT reconstruction.

    Parameters
    ----------
    None

    Returns
    -------
    params : `dict`
        Dictionary containing parameters for constructing the ODL geometry, including
        source/detector radii, pitch, detector and reconstruction volume bounds and shapes.
    
    geometry : `odl.tomo.geometry.conebeam.FanBeamGeometry`
        ODL geometry object corresponding to the system setup.

    space : `odl.uniform_discr`
        Discretized reconstruction space for the phantom volume.

    phantom_odl : `odl.Element`
        ODL-compatible phantom volume created from PyKatsevich's phantom data.

    ray_trafo : `odl.tomo.RayTransform`
        Ray transform operator constructed using the ASTRA CUDA backend.

    sinogram_odl : `odl.Element`
        Sinogram of the phantom generated using the ODL ray transform.

    sinogram_pykats_odl : `odl.Element`
        Sinogram generated by PyKatsevich, reshaped and cast into an ODL-compatible element.

    Notes
    -----
    - Assumes the PyKatsevich repository is available locally with specific path structure.
    - Requires a YAML configuration file defining geometry and phantom (e.g. `test01.yaml`).
    - Saves phantom and sinogram visualizations to `comparison/` directory.
    - Axes are aligned so that sinograms from PyKatsevich and ODL can be visually compared.
    - Designed for debugging and validating geometric consistency in reconstruction pipelines.
    """
    # Paths
    output_path = '/home/rosaca/code/odl/examples/kats/comparison/'
    os.makedirs(output_path, exist_ok=True)
    pykatsevich_path = '/home/rosaca/code/helical-kats/pykatsevich'
    test_path = '/home/rosaca/code/helical-kats/tests/'
    sys.path.append('/home/rosaca/code/helical-kats')

    # Load funcs of pykats
    spec_init = importlib.util.spec_from_file_location("initialize", os.path.join(pykatsevich_path, 'initialize.py'))
    initialize = importlib.util.module_from_spec(spec_init)
    spec_init.loader.exec_module(initialize)

    spec_phantom = importlib.util.spec_from_file_location("common", os.path.join(test_path, 'common.py'))
    common = importlib.util.module_from_spec(spec_phantom)
    spec_phantom.loader.exec_module(common)

    # load data of pykats
    with open(os.path.join(test_path, f'test0{str(test)}.yaml'), 'r') as f:
        yaml_settings = yaml.safe_load(f)
    phantom_settings = yaml_settings['phantom']
    voxel_size = phantom_settings['voxel_size']
    # print('voxel size:', voxel_size)

    # load geometry of pykats
    geom = yaml_settings['geometry']
    shape = (phantom_settings['columns'], phantom_settings['rows'], phantom_settings['slices'])
    kat_conf = initialize.create_configuration(geom,{'GridColCount': shape[0],
                                                'GridRowCount': shape[1],
                                                'GridSliceCount': shape[2],
                                                'option': {'WindowMinX': -shape[0]*voxel_size/2,
                                                        'WindowMaxX':  shape[0]*voxel_size/2,
                                                        'WindowMinY': -shape[1]*voxel_size/2,
                                                        'WindowMaxY':  shape[1]*voxel_size/2,
                                                        'WindowMinZ': -0.5 * geom['helix']['pitch_mm_rad'] * geom['helix']['angles_range'],
                                                        'WindowMaxZ':  0.5 * geom['helix']['pitch_mm_rad'] * geom['helix']['angles_range']}})
    
    phantom_pykats = common.phantom_objects_3d(phantom_settings['rows'], # ASTRA's convention 
                                                phantom_settings['columns'],
                                                phantom_settings['slices'],
                                                voxel_size=voxel_size,
                                                objects_list=phantom_settings['objects'])
    
    sinogram_pykats, vol_geom, proj_geom, vertical_shift = common.project(phantom_pykats, voxel_size, geom)

    space = odl.uniform_discr(min_pt=[
                                    vol_geom["option"]["WindowMinZ"],
                                    vol_geom["option"]["WindowMinY"],
                                    vol_geom["option"]["WindowMinX"]],
                                max_pt=[
                                    vol_geom["option"]["WindowMaxZ"],
                                    vol_geom["option"]["WindowMaxY"],
                                    vol_geom["option"]["WindowMaxX"]],
                                shape=[
                                    vol_geom["GridSliceCount"], # slice
                                    vol_geom["GridRowCount"], # row
                                    vol_geom["GridColCount"]], # cols
                                dtype='float32')
    min_pt=[vol_geom["option"]["WindowMinZ"],
            vol_geom["option"]["WindowMinY"],
            vol_geom["option"]["WindowMinX"]]
    max_pt=[vol_geom["option"]["WindowMaxZ"],
            vol_geom["option"]["WindowMaxY"],
            vol_geom["option"]["WindowMaxX"]]

    angles_per_turn = geom['helix']['angles_count'] * 2 * np.pi / geom['helix']['angles_range'] 

    params = {"SRC_RADIUS": geom['SOD'],
        "DET_RADIUS": geom['SDD'] - geom['SOD'],
        "PITCH": geom['helix']['pitch_mm_rad'] * 2 * np.pi,
        "DET_X_MIN": - geom['detector']['detector cols'] / 2 * geom['detector']['detector psize'],
        "DET_X_MAX":   geom['detector']['detector cols'] / 2 * geom['detector']['detector psize'],
        "DET_Z_MIN": - geom['detector']['detector rows'] / 2 * geom['detector']['detector psize'], 
        "DET_Z_MAX": + geom['detector']['detector rows'] / 2 * geom['detector']['detector psize'],
        "DET_NPX_X": geom['detector']['detector cols'], 
        "DET_NPX_Z": geom['detector']['detector rows'],
        "REC_MIN_X": -shape[0] * voxel_size / 2,
        "REC_MAX_X": shape[0] * voxel_size / 2,
        "REC_MIN_Y": -shape[1] * voxel_size / 2,
        "REC_MAX_Y": shape[1] * voxel_size / 2,
        "REC_MIN_Z": kat_conf['z_min'],
        "REC_MAX_Z": kat_conf['z_max'],
        "REC_NPX_X": shape[0],
        "REC_NPX_Y": shape[1],
        "REC_NPX_Z": shape[2],
        "ANGLES_PER_TURN": angles_per_turn,
        "DET_CURVATURE_RADIUS": None if not curved else geom['SDD'],
        "DET_PIXEL_SIZE": geom['detector']['detector psize']
        }
    
    if params['DET_CURVATURE_RADIUS'] is not None:
        params['DET_X_MIN'] = np.arctan(params['DET_X_MIN'] / params['DET_CURVATURE_RADIUS'])
        params['DET_X_MAX'] = np.arctan(params['DET_X_MAX'] / params['DET_CURVATURE_RADIUS'])
        # params['DET_X_MIN'] = np.arcsin(params['DET_X_MIN'] / (params['DET_CURVATURE_RADIUS']**2 + params['DET_X_MIN']**2)**0.5)
        # params['DET_X_MAX'] = np.arcsin(params['DET_X_MAX'] / (params['DET_CURVATURE_RADIUS']**2 + params['DET_X_MAX']**2)**0.5)
        curv = (params['DET_CURVATURE_RADIUS'], None)
        det_type = 'curved'
        x_axis = r'$\alpha$'
        min_pt = (params["DET_X_MIN"], params["DET_Z_MIN"]) # see astra_setup.py
        max_pt = (params["DET_X_MAX"], params["DET_Z_MAX"])
        shape_dpart = (params["DET_NPX_X"], params["DET_NPX_Z"])
        det_axes = [(0, 1, 0), (0, 0, 1)]
    else:
        curv = None
        det_type = 'flat'
        x_axis = 'u'
        min_pt = (params["DET_Z_MIN"], params["DET_X_MIN"]) # see astra_setup.py
        max_pt = (params["DET_Z_MAX"], params["DET_X_MAX"])
        shape_dpart = (params["DET_NPX_Z"], params["DET_NPX_X"])
        det_axes = [(0, 0, 1), (0, 1, 0)]
        # for how proj_geom is created,
        # rows are on first axis and cols on second (for flat)


    s_len = geom['helix']['angles_range']
    s_min = -s_len * 0.5
    s_max =  s_len * 0.5
    delta_s = 2 * np.pi / angles_per_turn # Turn in radians per projection 
    # angles = np.linspace(s_min, s_max, geom['helix']["angles_count"], dtype=np.float32)
    angles = s_min + delta_s * (np.arange(geom['helix']["angles_count"], dtype=np.float32) + 0.5 )  # only with nodes_on_bdry=True

    # print('angles pre geometry: ', angles[0])
    N_s = geom['helix']['angles_count']
    apart = odl.uniform_partition(angles[0], angles[-1], N_s, nodes_on_bdry=True)
    dpart = odl.uniform_partition(min_pt, max_pt, shape_dpart)

    R = params["SRC_RADIUS"]  # in mm
    s_min, s_max = angles[0], angles[-1] 
    range_s = s_max - s_min
    mean_src_x = (R / (2 * np.pi * range_s)) * (
                      np.sin(2 * np.pi * s_max) - np.sin(2 * np.pi * s_min))
    dx = 0 # 5.81828892
    # print(f"Mean source x-position: {mean_src_x} mm")
    if shifts is not None:
        print('using shifts')
        geometry = odl.tomo.ConeBeamGeometry(apart=apart,
                                            dpart=dpart,
                                            src_radius=params["SRC_RADIUS"],
                                            det_radius=params["DET_RADIUS"],
                                            det_curvature_radius=curv,
                                            pitch=params["PITCH"],
                                            src_shift_func=partial(odl.tomo.flying_focal_spot, apart=apart, shifts=shifts),
                                            det_shift_func=partial(odl.tomo.flying_focal_spot, apart=apart, shifts=shifts),
                                            src_to_det_init=(-1, 0, 0),
                                            det_axes_init=det_axes,
                                            vertical_shift=vertical_shift)
    else:
        geometry = odl.tomo.ConeBeamGeometry(apart=apart,
                                         dpart=dpart,
                                         src_radius=params["SRC_RADIUS"],
                                         det_radius=params["DET_RADIUS"],
                                         det_curvature_radius=curv,
                                         pitch=params["PITCH"],
                                         translation=(dx, 0, 0),
                                         src_to_det_init=(-1, 0, 0),
                                         det_axes_init=det_axes,
                                         vertical_shift=vertical_shift)

    # phantom_pykats has shape(rows, columns, slices) -> needs to be transposed to create
    #  the ODL phantom (slices, rows, columns)
    phantom_pykats_T = np.transpose(phantom_pykats, (2, 0, 1))

    if complex_phantom:
        ellipsoids = [
            # Central sphere
            [1.0, 0.6, 0.6, 0.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            # Tilted elongated ellipsoid
            [0.8, 0.4, 0.2, 0.7, 0.3, -0.2, 0.2, np.pi/4, np.pi/6, np.pi/3],
            # Outer ellipsoid of hollow shell
            [0.6, 0.5, 0.5, 0.5, -0.4, 0.4, -0.3, 0.0, np.pi/8, 0.0],
            # Inner ellipsoid of hollow shell (subtracted)
            [-0.6, 0.3, 0.3, 0.3, -0.4, 0.4, -0.3, 0.0, np.pi/8, 0.0]
        ]
        # phantom_odl = odl.phantom.ellipsoid_phantom(space, ellipsoids)
        phantom_odl = odl.phantom.shepp_logan(space, modified=True)
    else:
        phantom_odl = space.element(phantom_pykats_T) 
    

    ray_trafo = odl.tomo.RayTransform(space, geometry, impl='astra_cuda')
    sinogram_odl = ray_trafo(phantom_odl).asarray() 
    sinogram_pykats_T = np.transpose(sinogram_pykats, (1, 0, 2) if curv is None else (1, 2, 0))
    diff = sinogram_odl - sinogram_pykats_T

    # # study centering phantom
    # src_positions = geometry.src_position(angles)

    # # 2. Compute mean x-position of the source
    # mean_src_x = np.mean(src_positions[:, 0])
    # mean_src_y = np.mean(src_positions[:, 1])
    # mean_src_z = np.mean(src_positions[:, 2])

    # # 3. Get phantom domain center in x
    # phantom_center_x = 0.5 * (phantom_odl.space.domain[0].min() + phantom_odl.space.domain[0].max())
    # phantom_center_y = 0.5 * (phantom_odl.space.domain[1].min() + phantom_odl.space.domain[1].max())
    # phantom_center_z = 0.5 * (phantom_odl.space.domain[2].min() + phantom_odl.space.domain[2].max())
    # # 4. Compute shift needed to align phantom to source trajectory
    # dx = mean_src_x - phantom_center_x
    # dy = mean_src_y - phantom_center_y
    # dz = mean_src_z - phantom_center_z

    if diff.shape[1] == geom['detector']['detector rows']:
        diff = np.transpose(diff, (0, 2, 1))
    if curv is None:
        axes = ('u', 'w')
    else:
        axes = (r'$\alpha$', 'w')

    from  examples.kats.utils import save_side_by_side_video, save_uv_video
    if not os.path.exists(output_path + f'/{det_type}/'):
        os.makedirs(output_path + f'/{det_type}/')
    # print('Saving videos in : ', output_path + f'{det_type}/')
    # save_uv_video(diff, output_path + f'/{det_type}/', f'error_sino_{det_type}', step=10, cmap='grey', axes=axes)
    print('geometry and sino set up.')
    return params, geometry, space, phantom_odl, ray_trafo, sinogram_odl, kat_conf

def create_space_geom(curved=True, shift_func=None, config='full', ffs=False):

    # taken from pykats test03.yaml
    volCols = 560 # if config=='full' else 56
    volRows = 540 # if config=='full' else 54
    volSlices = 580 # if config=='full' else 58
    voxel_size = 0.032 # if config=='full' else 0.32

    angles_count = 512 if config=='full' else 128 # total number of angles in the helical trajectory
    angles_range = 7.084794 # in radians
    Rs = 50
    D = 80
    pitch_mm_rad = 5.25

    # detector
    detCols = 1056 if config=='full' else 128
    detRows = 928 if config=='full' else 116
    pixel_size = 0.078125 if config=='full' else 0.3125 # 0.078125 # detector pixel size in mm

    minX = -volCols * voxel_size / 2
    maxX = volCols * voxel_size / 2
    minY = -volRows * voxel_size / 2
    maxY = volRows * voxel_size / 2
    minZ = -volSlices * voxel_size / 2
    maxZ = volSlices * voxel_size / 2

    # print(f"({minZ}, {maxZ}) should be inside ({-0.5 * pitch_mm_rad * angles_range}, {0.5 * pitch_mm_rad * angles_range})")
    # assert that -0.5 * pitch_mm_rad * angles_range <= minZ <= maxZ <= 0.5 * pitch_mm_rad * angles_range, \
    
    assert -0.5 * pitch_mm_rad * angles_range <= minZ <= maxZ <= 0.5 * pitch_mm_rad * angles_range

    space = odl.uniform_discr(min_pt=[minZ, minY, minX],
                              max_pt=[maxZ, maxY, maxX],
                              shape=[volSlices, volRows, volCols], 
                              dtype='float32')
    
    angles_per_turn = angles_count * 2 * np.pi / angles_range

    params = {"SRC_RADIUS": Rs,
        "DET_RADIUS": D - Rs,
        "PITCH": pitch_mm_rad * 2 * np.pi,
        "DET_X_MIN": - detCols / 2 * pixel_size,
        "DET_X_MAX":   detCols / 2 * pixel_size,
        "DET_Z_MIN": - detRows / 2 * pixel_size, 
        "DET_Z_MAX":   detRows / 2 * pixel_size,
        "DET_NPX_X":   detCols, 
        "DET_NPX_Z":   detRows,
        "REC_MIN_X":   minX,
        "REC_MAX_X":   maxX,
        "REC_MIN_Y":   minY,
        "REC_MAX_Y":   maxY,
        "REC_MIN_Z":   -0.5 * pitch_mm_rad * angles_range,
        "REC_MAX_Z":    0.5 * pitch_mm_rad * angles_range,
        "REC_NPX_X": volCols,
        "REC_NPX_Y": volRows,
        "REC_NPX_Z": volSlices,
        "ANGLES_PER_TURN": angles_per_turn,
        "DET_CURVATURE_RADIUS": None if not curved else D,
        "DET_PIXEL_SIZE": pixel_size
        }
    
    if params['DET_CURVATURE_RADIUS'] is not None:
        params['DET_X_MIN'] = np.arctan(params['DET_X_MIN'] / params['DET_CURVATURE_RADIUS'])
        params['DET_X_MAX'] = np.arctan(params['DET_X_MAX'] / params['DET_CURVATURE_RADIUS'])
        curv = (params['DET_CURVATURE_RADIUS'], None)
        min_pt = (params["DET_X_MIN"], params["DET_Z_MIN"]) # see astra_setup.py
        max_pt = (params["DET_X_MAX"], params["DET_Z_MAX"])
        shape_dpart = (params["DET_NPX_X"], params["DET_NPX_Z"])
        det_axes = [(0, 1, 0), (0, 0, 1)]
    else:
        curv = None
        min_pt = (params["DET_Z_MIN"], params["DET_X_MIN"]) # see astra_setup.py
        max_pt = (params["DET_Z_MAX"], params["DET_X_MAX"])
        shape_dpart = (params["DET_NPX_Z"], params["DET_NPX_X"])
        det_axes = [(0, 0, 1), (0, 1, 0)]

    s_len = angles_range
    s_min = -s_len * 0.5
    delta_s = 2 * np.pi / angles_per_turn # Turn in radians per projection 
    angles = s_min + delta_s * (np.arange(angles_count, dtype=np.float32) + 0.5 )  # only with nodes_on_bdry=True
    N_s = angles_count
    apart = odl.uniform_partition(angles[0], angles[-1], N_s, nodes_on_bdry=True)
    
    # apart = odl.nonuniform_partition(angles)
    dpart = odl.uniform_partition(min_pt, max_pt, shape_dpart)

    src_shift_func = None
    det_shift_func = None
    # --- Non-constant pitch (z-shift) ---
    if shift_func is not None:
        if ffs:
            raise ValueError("Don't test pitch and ffs at the same time.")
        shift_func = partial(odl.tomo.flying_focal_spot, apart=apart, shifts=shift_func)
        src_shift_func = shift_func
        det_shift_func = shift_func
    
    # --- Flying focal spot (synthetic alternating pattern) ---
    if ffs:
        offset_angular = np.tile([np.deg2rad(0.021), np.deg2rad(0.02)], angles_count // 2)  
        offset_radial = np.tile([0.0, 0.4], angles_count // 2)              
        offset_axial = np.tile([0.0, 0.06], angles_count // 2) 

        src_radius = params["SRC_RADIUS"]
        pitch = params["PITCH"]

        det_offset_axial = (offset_axial + angles / (2 * np.pi) * pitch)               

        # Compute along-axis offset
        offset_along_axis = - angles[0] / (2 * np.pi) * pitch 

        # Source shifts
        shift_d = np.cos(-offset_angular) * (src_radius + offset_radial) - src_radius
        shift_t = np.sin(-offset_angular) * (src_radius + offset_radial)
        print(shift_d[0:10], shift_t[0:10])
        # Approximate z pitch correction
        shift_z = -(det_offset_axial - angles / (2 * np.pi) * pitch - offset_along_axis)
        shift_r = shift_z - offset_axial

        shift_angle = 0.0013325066936852141

        # Define src and det shift functions
        shifts = np.transpose(np.vstack([shift_d, shift_t, shift_r]))
        R = np.array([
        [np.cos(shift_angle), -np.sin(shift_angle)],
        [np.sin(shift_angle),  np.cos(shift_angle)]
        ])
        shifts[:, :2] = shifts[:, :2] @ R.T
        src_shift_func = partial(odl.tomo.flying_focal_spot, 
                                 apart=apart, shifts=shifts)

        # detector shifts
        det_axes = [(np.cos(shift_angle), np.sin(shift_angle), 0),
                     (0, 0, 1)]
        shift_d_det = D * (np.cos(shift_angle) - 1)
        shift_t_det = D * np.sin(shift_angle)
        n_angles = len(angles)
        shifts_det = np.transpose(np.vstack([
            np.ones(n_angles) * shift_d_det,
            np.ones(n_angles) * shift_t_det,
            shift_z]))
        det_shift_func = partial(odl.tomo.flying_focal_spot, 
                                 apart=apart, shifts=shifts_det)
        
        
    geometry = odl.tomo.ConeBeamGeometry(apart=apart,
                                         dpart=dpart,
                                         src_radius=params["SRC_RADIUS"],
                                         det_radius=params["DET_RADIUS"],
                                         det_curvature_radius=curv,
                                         pitch=params["PITCH"],
                                         src_shift_func=src_shift_func,
                                         det_shift_func=det_shift_func,
                                         src_to_det_init=(-1, 0, 0), # src_to_det_init = (-np.cos(shift_angle), -np.sin(shift_angle), 0), # 
                                         det_axes_init=det_axes)
    
    return params, space, geometry
